trigger:
  branches:
    include:
      - main

pool: Adrian-PC

steps:
- script: |
    echo "##[debug] System Default Working Directory: $(System.DefaultWorkingDirectory)"
    echo "##[debug] Build Artifact Staging Directory: $(Build.ArtifactStagingDirectory)"
    dir
- task: CopyFiles@2
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
     artifactName: drop
- task: Docker@2
  inputs:
    containerRegistry: 'GoCheatContainerRegistry'
    repository: 'GoCheatServer'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'