trigger:
  branches:
    include:
      - master

pool: Adrian-PC

steps:
- script: |
    echo "##[debug] System Default Working Directory: $(System.DefaultWorkingDirectory)"
    echo "##[debug] Build Artifact Staging Directory: $(Build.ArtifactStagingDirectory)"
    dir
- task: CopyFiles@2
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
     artifactName: drop
- task: Docker@2
  inputs:
    containerRegistry: 'GoCheatACRServiceConnectionServicePrincipal'
    repository: 'gocheatclient'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
- task: AzureContainerApps@1
  inputs:
    azureSubscription: 'GoCheatServiceConnection'
    containerAppName: 'gocheatcontainerapp'
    resourceGroup: 'GoCheat'
    containerAppEnvironment: 'gocheat-env'
    imageToDeploy: 'gocheatregistry.azurecr.io/gocheatclient:latest'
    acrName: 'gocheatregistry'
    acrUsername: 'GoCheatRegistry'
    acrPassword: $(acrPassword)
    targetPort: '3000'
    environmentVariables: NEXT_PUBLIC_DOMAIN=gocheat.azurewebsites.net NEXT_PUBLIC_GO_BACKEND=gocheatserver.azurewebsites.net