trigger:
  branches:
    include:
      - master

pool: Adrian-PC

steps:
- script: |
    echo "##[debug] System Default Working Directory: $(System.DefaultWorkingDirectory)"
    echo "##[debug] Build Artifact Staging Directory: $(Build.ArtifactStagingDirectory)"
    dir
- task: CopyFiles@2
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
     artifactName: drop
- task: Docker@2
  inputs:
    containerRegistry: 'GoCheatContainerRegistry'
    repository: 'GoCheatClient'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'Azure subscription 1(36ed3de6-9239-4dbf-92c7-9ec5f09a2323)'
    appName: 'GoCheatClient'
    resourceGroupName: 'GoCheat'
    containers: 'gocheatregistry.azurecr.io/gocheatclient:latest'